language: go

go:
  - "1.10"

services:
  - docker

install:
  - env
  - pwd
  - echo $GOPATH
  - go get -u golang.org/x/lint/golint
  - go get -u github.com/golang/dep/cmd/dep

script:
  - dep status
  - dep ensure
  - golint
  - go vet
  - go test -race -coverprofile=coverage.txt -covermode=atomic
  - go build
  # Let's verify that docker image is buildable
  - docker build -t test .

after_success:
  - bash <(curl -s https://codecov.io/bash)
